# Generated by Django 3.1.3 on 2020-11-29 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immunocore_app', '0002_auto_20201128_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.CharField(max_length=10000)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immunocore_app.gene')),
            ],
        ),
    ]
